#!/bin/bash

# Shell Options

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and update LINES and COLUMNS
shopt -s checkwinsize

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Enable extended globbing
shopt -s extglob

# Case-insensitive globbing
shopt -s nocaseglob

# Warn when shifting past the number of positional parameters
shopt -s shift_verbose

# Include dotfiles in globbing
shopt -s dotglob

# Enable recursive globbing with **
shopt -s globstar 2>/dev/null

# Prevent file overwrite on stdout redirection
set -o noclobber

# Update LINES and COLUMNS after each command
shopt -s checkwinsize

# Enable vi mode (comment out if you prefer emacs mode)
# set -o vi

# Better tab completion
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"
bind "set mark-symlinked-directories on"

# History search with arrow keys
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

# Disable Ctrl-S (XOFF)
stty -ixon